#!/usr/bin/env bash

set -euo pipefail

export sha=$(cat .git/refs/heads/main)
npm run build
pushd ../${subdomain:-}livemusiclocator.github.io
git pull
rm -rf index.html
rm -rf 404.html
rm -rf assets
cp -r ../lml_frontend_client/dist/* .
cp index.html 404.html
git add .
git commit -m "Release ${sha}"
git push
popd
