#!/usr/bin/env bash

set -euo pipefail

export sha=$(cat .git/refs/heads/main)
npm run build
pushd ../livemusiclocator.github.io
git pull
rm -rf index.html
rm -rf assets
cp -r ../lml_frontend_client/dist/* .
git add .
git commit -m "Release ${sha}"
git push
popd
